# ---------------------------------------------------- #
# ---------------- TESTING PROFILE --------------- #
# ---------------------------------------------------- #

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/work_connect_test
    username: your_test_user
    password: your_test_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
