# ---------------------------------------------------- #
# ---------------- PRODUCTION PROFILE --------------- #
# ---------------------------------------------------- #

spring:
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
